version: '3.8'

services:
  postgres:
    image: postgres:alpine3.18
    container_name: postgres-app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Follow123
      - POSTGRES_DB=postgresdb
    restart: always
    ports:
      - "5433:5432"
    networks:
      - general
  api:
    build: .
    container_name: fastapi-application
    command: bash -c "ls && cd app && alembic revision --autogenerate -m 'Init' && alembic upgrade head && cd ../ && uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level 'trace'"
    environment:
      PORT: 8000
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - general
networks:
  general:
    driver: bridge